# Kevin Krummenauer 2016
language: java
jdk:
  - oraclejdk8
  
cache:
  directories:
  - $HOME/.m2
  
script:
  - mvn clean deploy --settings settings.xml -P profilewhiledo
  
env:
  global:
    - secure: Cmg88AW+qw0veeY8olItu3nZOflhxhAA/ymdYOz7NcaTB6Ib7q8Hk01ESyaJ7lb5l1ZA0klzPyjLAtukZVQ1TvKkLN76GxHldLJ7kJAxtg3Jn5g/HOaWZbHTH1RmFpxqKMrg9MaezuJKowfZZqjWlxj279bhraMpEQ9dA9pJ33eXGlI0fzPbZMcIBEu5litu2TJGe67HoOe1XRYHhNBrGU4wCs9g2pdxsUVY2zVkMWFqpHiGcpDGp0Y1hX9xhf0OIKQ9KBOCd1VC6IMpyJ8bCLwCzwreQsri4DqjE16aLyHfjcclCv/IimouA/yT0ELzT8K9KMMD3nhAQPrqutxC/T8+kHc/ZJqemr7kLGtSFvAXjB5eUYnH7TF42UOvlgZSigp8h3BPkjDXxyQY6ggLJvEoEIMEk/fBy47gbAPi4sFWF8MBdafQBdWIMrrXho3vyIAXqHBQLGFJTgVSSLFU9m6kI3gc8u8uAw+tZvvNSo9Bktp0ZMUsj/7UiIFFPg3MgQjRprmM1EfzWcFmAYIfPnG5EkW1d/XO7dWZx3Qay1IcUJqt7veKR1GLpq9uG2A/WSOZXQzMvaoui94W5deDGprGzcXnbqKzaX8Nt4iQu4rPWMNoZsjFCfS+XIJkkUgK56wczSk3SPg389aexB4VwoBUaBojAQCUjau1eEc7S+U=
    - secure: icqMmwQA2KCX2YYDdM2yTdhKQsKzW60Cm3RzMZah9qro9L0/wc4VWSfuRQhsfPwFvqszVTzENqP4MjSrG7WBuzQ8tVZM9WrxTUKtbqEEKDedNOECzqYEVORL6J5AC+MD/XKl0G27wPaTovF3AQsae9HDiIx74ZNEjjFF7TRhBjDj3zpe/Ifdr4lqKZ3iw0YFro7FxWIGTuaWW3YP2HNl/l3RbBZSeU6LAw3OI74b6kyMGlXXEvG1fNU3f8T1svkxaOfZgdMxSDjhAek1z9EgojZosGTki21bR4V46iz/91zORxuWV+cxRRqSGouCcWA7KNMAMGuvkzltzJ0kFdnBx8QfqaEazZX05RQzHd8Yi31Ixoy2TPlcVHMxnjt8Q5DV+ZuiZqi/BOLBnQNTUmbbvPKtbhl4D7C+YF72dXQCWgd8VJmbpkynkDZ39dRxN4QND5Gk+Hytbn7YEK1HGX6qPIIFxZgcPOsXz//RTAhfZRves++CY+tPK/n/ZvN+c3eD0sQYIlB12GJGLoiMRAGkZsJKUjQvKCxDzXMCkrQDWdSToxYQ4EvtOYbnhO9TuohfsiQkyo6p+MFPT/OJ7R0GFK8zzF41c7fl7bgNkYyPNrUljS8tGgJJvMh7YA8QGmzEaetuKJvkuad2lBiHgeE6/UxWB6Isnwj6Nis4Eh4C38E=
